--
title: "A little bit about me"
2022-06-10
author: William Anil
email: wanil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  My name is William Anil.
  Snap code: b4obama
  Instagram: w_i_l_l_0_3_3
  
  1.
  I have been playing soccer since I was 4. Now I have been on the township team for about seven years. I find the the sport to be extremely fun and liberating.
 
 2.
  I have been playing the violin since fourth grade in school. I still take Orchestra today. It is nice to be part of an ensemble with my friends.
 
 3.
  I have volunteered in many places over the past two years, including Playhouse 22, Heavenly Farms and multiple East Brunswick elementary schools. 

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
--
