title: A little bit abou tme
author: William Anil
email: wanil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 lementary schools. 

theme: minima
Snap code: b4obama
Instagram: w_i_l_l_0_3_3

show_excerpts: true # set to false to remove excerpts on the homepage
